server:
  port: 9090
  webroot: "../frontend/dist/index.html"
  tls:
    cert_file: "certs/certificate.pem"
    key_file: "certs/private.pem"
static_routes:
  public:
    - path: "/web"
      dir: "../frontend/dist"
  private:
    - path: "/diary"
      dir: "../doc/build/html"
commands:
  - name: "make_calendar"
    desc: "make a calendar"
  - name: "draw_mindmap"
    desc: "draw a mindmap"
  - name: "ask_question"
    desc: "ask a question"
  - name: "write_blog"
    desc: "write a blog"
tasks:
  - name: "check task"
    schedule: "0 0 * * * *"  # Every 1 minute
    function: "checkTask"

