# Email Templates Configuration
# This file contains all email templates used by the application
# Variables can be used in templates with {{.VariableName}} syntax

templates:
  # Email confirmation template
  email_confirmation:
    subject: "Confirm Your Email Address"
    body: |
      Welcome to {{.AppName}}, {{.Username}}!

      Thank you for registering with us. To complete your registration, please confirm your email address by clicking the link below:

      {{.ConfirmURL}}

      This confirmation link will expire in 24 hours ({{.ExpiryTime}}).

      If you didn't register for this account, please ignore this email.

      After confirming your email, your registration will be reviewed by our administrators for approval.

      Best regards,
      The {{.AppName}} Team

  # Registration approval notification (to user)
  registration_approval:
    subject: "Registration {{.Status}} - {{.AppName}}"
    body: |
      Dear {{.Username}},

      {{if .Approved}}
      Congratulations! Your registration has been approved.

      You can now log in to the system using your credentials.

      Username: {{.Username}}
      Email: {{.Email}}

      Welcome to {{.AppName}}!
      {{else}}
      We regret to inform you that your registration has been denied.

      Username: {{.Username}}
      Email: {{.Email}}

      {{if .Reason}}
      Reason: {{.Reason}}
      {{end}}

      If you have any questions, please contact our support team.
      {{end}}

      Best regards,
      The {{.AppName}} Team

  # New registration notification (to admin)
  new_registration_notification:
    subject: "New User Registration - Approval Required"
    body: |
      New User Registration

      A new user has registered and is awaiting approval.

      User Details:
      - Username: {{.Username}}
      - Email: {{.Email}}
      - Realm ID: {{.RealmID}}
      - Registration Time: {{.RegistrationTime}}
      - Status: {{.Status}}

      Please log in to the admin panel to review and approve/deny this registration.

      Admin Panel: {{.AdminPanelURL}}

      Best regards,
      System Notification

  # Password reset template (for future use)
  password_reset:
    subject: "Password Reset Request - {{.AppName}}"
    body: |
      Dear {{.Username}},

      You have requested a password reset for your account.

      Please use the following link to reset your password:
      {{.ResetURL}}

      This reset link will expire in {{.ExpiryHours}} hours ({{.ExpiryTime}}).

      If you did not request this password reset, please ignore this email.

      Best regards,
      The {{.AppName}} Team

  # Welcome email (for future use)
  welcome:
    subject: "Welcome to {{.AppName}}!"
    body: |
      Dear {{.Username}},

      Welcome to {{.AppName}}! Your account has been successfully activated.

      Here are some helpful links to get you started:
      - Dashboard: {{.DashboardURL}}
      - User Guide: {{.UserGuideURL}}
      - Support: {{.SupportURL}}

      If you have any questions, please don't hesitate to contact our support team.

      Best regards,
      The {{.AppName}} Team

# Application configuration for templates
app:
  name: "Lazy Rabbit Secretary"
  base_url: "http://localhost:8080"
  admin_panel_url: "/admin/registrations"
  dashboard_url: "/dashboard"
  user_guide_url: "/help"
  support_url: "/support"
  support_email: "support@example.com"

# Default template variables
defaults:
  app_name: "Lazy Rabbit Secretary"
  expiry_hours: 24
  time_format: "2006-01-02 15:04:05 MST"
