version: '3.8'

services:
  postgres:
    image: postgres:15 # Use the desired PostgreSQL version
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data using a named volume

volumes:
  postgres_data:
    driver: local