version: "3"
services:
  nginx:
    # default ports 80, 443 - expose mapping as needed to host
    image: nginx:1.13-alpine
    container_name: lazy_rabbit_nginx
    restart: unless-stopped

    ports:
      - "1980:80"    # http
      - "1981:443"   # https
    volumes:
      - ../frontend:/var/www/html/web
      - ${NGINX_CONF}:/etc/nginx/conf.d/default.conf
      - ${NGINX_SSL_CERTS}:/etc/ssl:ro
      - ${NGINX_LOGS}:/var/log/nginx
    depends_on:
      - web

  web:
    container_name: lazy_rabbit_reminder
    build: ../backend
    ports:
      - "18080:8080"
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      - db
      - redis

  db:
    container_name: lazy_rabbit_db
    image: mariadb:10-focal
    # If you really want to use MySQL, uncomment the following line
    #image: mysql:8
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=${DB_PWD}  

    expose:
      - 3306
      - 33060
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    container_name: lazy_rabbit_redis
    image: redis:7.2.5-alpine
    restart: always
    ports:
      - "${REDIS_PORT}:6379"

volumes:
    db_data:
      driver: local  

