# 开发环境配置
spring:
  # 使用 H2 内存数据库
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    hibernate:
      # 自动创建、更新和验证数据库模式
      ddl-auto: create-drop
    # 显示生成的 SQL 语句
    show-sql: true

# Logback 配置
logging:
  level:
    root: info
  config: classpath:logback-test.xml

# 其他开发环境特定配置...